# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 00:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name=b'date published'),
        ),
        migrations.AddField(
            model_name='phase',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name=b'date published'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name=b'date published'),
        ),
    ]
